---
- name: Update and reboot Ubuntu host
  hosts: all
  become: yes
  become_user: root

  tasks:
  
    - name: Print Current User
      command: whoami
      register: current_user

    - debug:
        msg: "Current user is {{ current_user.stdout }}"
  
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: safe
      register: apt_upgrade_result

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the host if needed
      reboot:
        msg: "Rebooting due to package updates"
      when: reboot_required.stat.exists and apt_upgrade_result.changed
